- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: true
    tags:
    - node
    - zsh
  tasks:
  - include: ansible-tasks/zsh.yml
  - include: ansible-tasks/node.yml
  - include: ansible-tasks/nvim.yml
